### ISSUE TITLE
How do I run this project？

### ISSUE THREAD

**Issue by ZhaoZeWen** [bpmn-io/bpmn-moddle-auto-layout#14]
After downloading this example, how do I run the project with NPM install?

**Comment by philippfromme** [comment]
You can run `example.js` to lay out an example diagram. This project is not being maintained anymore, otherwise, there would be a proper development setup.

**Comment by pinussilvestrus** [comment]
I'll close this one since no real issue is reported. Feel free to re-open if needed.

**Comment by ZhaoZeWen** [comment]
> You can run `example.js` to lay out an example diagram. This project is not being maintained anymore, otherwise, there would be a proper development setup.

Running example.js alone through node doesn't work. How do you package and compress the entire project into a js file? Thank you for your reply！

**Comment by pinussilvestrus** [comment]
Like the example reveals, you can simply require the [`index.js`](https://github.com/bpmn-io/bpmn-moddle-auto-layout/blob/master/index.js) to use the module. You can use it then wherever you want.

**Comment by ZhaoZeWen** [comment]
> 如示例所示，您只需要求[`index.js`](https://github.com/bpmn-io/bpmn-moddle-auto-layout/blob/master/index.js)使用模块即可。您可以随时随地使用它，而无需[发布](https://hackernoon.com/publish-your-own-npm-package-946b19df577e)它。

Thank you very much for your reply!
