### ISSUE TITLE
Elements with nested Children are not supported

### ISSUE THREAD

**Issue by hoferch91** [bpmn-io/bpmn-moddle-auto-layout#3]
breadthFirstSearch should recursivly be called when elements have children e.g.
1. visit element, if (elementHasChildren) { go to 2. } else { go to 4. }
2. start breadthFirstSearch with the children (startEvent is required) and layout children
3. resize parent
4. layout element

**Comment by pinussilvestrus** [comment]
Closed via 91d1a95
