### ISSUE TITLE
Status of this library

### ISSUE THREAD

**Issue by kleinph** [bpmn-io/bpmn-moddle-auto-layout#8]
What is the status of this library? Is it maintained anymore?

It seems quite outdated. The _bpmn-moddle_ upstream lib used is ancient (0.12.2 vs 5.1.6) and misses also the switch to ES6 modules.

There are also BPMN elements which are not supported:
- lanes
- text annotations
- multiple start events
- maybe some more ...

Then there are also bugs as #5, and missing tests and no published package as in #1.

So, would it be appreciated to modernize this lib and fix some of this outstanding issues? Would be pull request be taken?

Thanks

**Comment by pinussilvestrus** [comment]
Hi @kleinph 

as you say correctly, this module isn't very maintained right now. It seems also not to be used quite much. We will discuss internally whether to investigate in updates or to mark it as deprecated.  Stay tuned 🥁 

We are always open for external contribution, so if you're interested to open pull request regarding the issues you mentioned,  feel free! We would appreciate it. 🎉

**Comment by kleinph** [comment]
Hi @pinussilvestrus 
thanks for the response! :)

Regarding PRs, are there any guidelines or codestyles to follow when modernizing the codebase? I have done a bit of work (getting rid of lodash, using ES6 features) and can send a PR soon.

**Comment by pinussilvestrus** [comment]
You can refer to this [guideline](https://github.com/bpmn-io/bpmn-js/blob/master/.github/CONTRIBUTING.md#code-style) :+1:

**Comment by pinussilvestrus** [comment]
Hi @kleinph,
we conclude to not support this project officially anymore, we will add a note for this. However, you are still welcome to contribute! 👍

**Comment by kleinph** [comment]
So as I understand PRs are still taken for bug fixes and new features/enhancements. Do the PRs have then to conform to the guideline you linked? (I have used some ES6 code before you mentioned the guideline, but it's no problem to rework it.)

BTW: I hope it's ok to comment on a closed issue.

**Comment by pinussilvestrus** [comment]
Follow our guidelines are always a good idea 👍🏻es6 features are of course allowed, we updated many of our libraries to es6 modules 🙂

**Comment by kleinph** [comment]
The linked guideline says in bold letters that no other ES6 construct than imports should be used.

**Comment by nikku** [comment]
> The linked guideline says in bold letters that no other ES6 construct than imports should be used.

Good catch. 

For our libraries use ES modules, do not use any ES6 features that require transpiling. Reason: Prevent overhead when transpiling to ES5 target browsers.
